### ISSUE TITLE
Help with PPC build

### ISSUE THREAD

**Issue by paulobaptista** [funkey/waterz#13]
Can't run sample code

```
$ python test.py
Re-using already compiled waterz version
Traceback (most recent call last):
  File "../test.py", line 4, in <module>
    segmentations = waterz.agglomerate(d, [100])
  File "/conda/user1/envs/w1/lib/python3.6/site-packages/waterz-0.9.5-py3.6-linux-ppc64le.egg/waterz/__init__.py", line 254, in agglomerate
    return __import__(module_name).agglomerate(
AttributeError: module 'waterz_45a18aa8cfa51f4bba85804d24319f4e' has no attribute 'agglomerate'
```
```

$ cat test.py
import waterz
import numpy as np
d = np.load("/plane_z0.npy")
segmentations = waterz.agglomerate(d, [100])
```

Built this way:

```
cd boost
wget https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz
tar xvf boost_1_77_0.tar.gz
cd ~
git clone https://github.com/funkey/waterz.git
cd waterz
python setup.py build_ext -I ~/boost/boost_1_77_0/
python setup.py install
```

OR I tried updating setup.py with
```

boost_dir = os.environ.get("BOOST_ROOT", None)
if boost_dir:
  boost_dir = os.path.join(boost_dir, 'boost')
  include_dirs.insert(1, boost_dir)
```

and set BOOST_ROOT with  ~/boost/boost_1_77_0/

**Comment by paulobaptista** [comment]
The solution on IBM RedHat Power 9 system is to

```yum install boost-devel
git clone
python setup.py install```
